# Site settings
title: Bryce Mehring
description: I'm Bryce Mehring and I love developing video games that create meaningful experiences.
footer_title: <a href="https://www.goldbargames.com/">Goldbar Games</a> Developer
email: brycemehring@gmail.com
github_username: BryceMehring
exclude: [README.md, CNAME, Gemfile]

url: //www.brycemehring.me

# Google Analytics
google_analytics_id: UA-52920015-1

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap

sass:
    style: :compressed
