# Site settings
title: Bryce Mehring
description: I'm Bryce Mehring and I love developing video games that create meaningful experiences.
email: brycemehring@gmail.com
github_profile: https://github.com/BryceMehring
exclude: [README.md, CNAME, Gemfile]

url: https://www.brycemehring.com

# Google Analytics
google_analytics_id: UA-52920015-1

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
    style: :compressed
