# Site settings
title: Bryce Mehring
footer_title: <a href="http://arithmebit.com/">ArithmeBit</a> Developer
email: brycemehring@gmail.com
github_username: BryceMehring
exclude: [README.md]

# Build settings
markdown: kramdown
permalink: pretty
